### ISSUE TITLE
стратегия не соединяется с ЛР

### ISSUE THREAD

**Issue by SourceOfDeath** [MailRuChamps/raic#76]
Здравствуйте!
При запуске ЛР в консоли вижу:

INFO - Waiting for client on port 31001
INFO - Guessed window DPI factor: 1
INFO - GL version: "4.4.0 - Build 21.20.16.4565"

вроде нормально. В Eclipse нажимаю Run - ЛР в консоли пишет

INFO - Client connected on port 31001
ERROR - Player down: trailing characters at line 1 column 228

Eclipse в консоли пишет 

<terminated> New_configuration (1) C:\Program Files\Java\jre1.8.0_191\bin\javaw.exe

создаётся впечатление, что стратегия проработала один цикл while в Ranner.java  и корректно завершилась. При запуске стратегии без ЛР в консоли вижу (ожидаемо)

Exception in thread "main" java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at RemoteProcessClient.<init>(RemoteProcessClient.java:18)
	at Runner.<init>(Runner.java:16)
	at Runner.main(Runner.java:12)

Уменя: Windows7x64 SP1, java version "1.8.0_191", Eclipse Version: 2018-12 (4.10.0) Build id: 20181214-0600
В связи с вышеизложенным, у меня два вопроса: кто виноват и что делать? Заранее благодарен.

**Comment by mixei4** [comment]
Зачем гадать, где завершилась стратегия, можно же продебажить построчно и понять где конкретно падает.

**Comment by kuviman** [comment]
> ERROR - Player down: trailing characters at line 1 column 228

Произошла ошибка в протоколе взаимодействия клиента с ЛР

Воспроизводится ли со стандартной стратегией (пустой)? Последняя ли у вас версия ЛР/java-пакета?

**Comment by SourceOfDeath** [comment]
kuviman, огромное спасибо! Качал ЛР и стратегию с разницей в 3 дня. Перекачал сейчас-всё заработало!
